print("TONG DOAN DAI DUNG")
print("msv:24575202161009")
ds = input("Nhập các phần tử của list (cách nhau bằng khoảng trắng): ").split()
print("\nList ban đầu:", ds)
them = input("thêm phần tử: ")
ds.append(them)
print("list sau khi thêm phần tử: ", ds)
