print("Tong doan dai dung")
print("msv:24575202161009")
ds = input("Nhập các phần tử của list (cách nhau bằng khoảng trắng): ").split()
print("\nList ban đầu:", ds)
ds.sort()
print("\nList sau khi sắp xếp:", ds)
